
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/lib/emsdk/"
      - "/usr/lib/emsdk/upstream/emscripten/"
      - "/home/nikolas/.rbenv/shims/"
      - "/home/nikolas/bin/"
      - "/home/nikolas/.local/bin/"
      - "/usr/local/bin/"
      - "/home/nikolas/.cargo/bin/"
      - "/usr/bin/"
      - "/bin/"
    searched_directories:
      - "/usr/lib/emsdk/uname"
      - "/usr/lib/emsdk/upstream/emscripten/uname"
      - "/home/nikolas/.rbenv/shims/uname"
      - "/home/nikolas/bin/uname"
      - "/home/nikolas/.local/bin/uname"
      - "/usr/local/bin/uname"
      - "/home/nikolas/.cargo/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/lib/emsdk"
        - "/usr/lib/emsdk/upstream/emscripten"
        - "/home/nikolas/.rbenv/shims"
        - "/home/nikolas/bin"
        - "/home/nikolas/.local/bin"
        - "/usr/local/bin"
        - "/home/nikolas/.cargo/bin"
        - "/usr/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.12.47-1-lts - x86_64
...
